# Per-meter results

## Stress-match on test-set

In [2]:
import pandas as pd

In [9]:
infi_test = "../../../out/scansion_gl_eval_202.annot.tsv"

In [10]:
test_df = pd.read_csv(infi_test, sep="\t")

In [11]:
test_df

,sIdx,txt,gld,prd,wdiffs,emt,vmt,smt,gmt,mmt,slh,dlp,syn,die,slp,slc,ndb,gsy,psy,eqf
0,0,Cal olido de rosas que sai d’antr’ó ramaxen,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,0,0,0,0,0,0,14,14,NaN
1,1,"Nun-ha mañan de Mayo, hay amores soaves",NaN,NaN,NaN,NaN,NaN,1,NaN,1,0,1,0,0,0,0,1,14,14,NaN
2,2,"Que n’inda vir se sinten, nin se ve cand’entraren",NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,0,0,0,0,0,0,14,14,NaN
3,3,Po-la mimosa porta qu’ó corazon lles abre,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,0,0,0,0,0,0,14,14,NaN
4,4,"De seu, cal s’abre n’o agosto",NaN,NaN,NaN,NaN,NaN,0,NaN,1,1,0,0,0,0,0,0,8,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,Non hai no mundo un pobo regalado,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,0,0,0,0,0,0,11,11,NaN
796,796,por natureza com'o meu terreo.,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,0,0,0,0,0,0,11,11,NaN
797,797,"Navallas, bucareus e caramuxos,",NaN,NaN,NaN,NaN,NaN,1,NaN,1,0,0,0,0,0,0,0,11,11,NaN
798,798,"parrochas, birbirichos e barbadas",NaN,NaN,NaN,NaN,NaN,1,NaN,1,0,0,0,0,0,0,0,11,11,NaN
799,799,"percebes, panchos, pragos e curuxos",NaN,NaN,NaN,NaN,NaN,1,NaN,1,0,0,0,0,0,0,0,11,11,NaN

In [12]:
test_df.columns

Index(['sIdx', 'txt', 'gld', 'prd', 'wdiffs', 'emt', 'vmt', 'smt', 'gmt',
       'mmt', 'slh', 'dlp', 'syn', 'die', 'slp', 'slc', 'ndb', 'gsy', 'psy',
       'eqf'],
      dtype='object')

In [13]:
test_df['smt'] = test_df['smt'].astype(int)  # ensure numeric 0/1

result_test = (
    test_df.groupby('gsy')
      .agg(
          smt_ones=('smt', 'sum'),          # total 1s
          count=('smt', 'size')             # total rows in group
      )
)

# percentage of 1s within each gmt group
result_test['smt_pct'] = result_test['smt_ones'] / result_test['count'] * 100

In [14]:
result_test

     smt_ones  count     smt_pct
gsy
3           8      8  100.000000
4          16     18   88.888889
5          48     59   81.355932
6         101    114   88.596491
7          54     60   90.000000
8         211    266   79.323308
10         54     69   78.260870
11        123    163   75.460123
12         12     20   60.000000
14         20     23   86.956522

## Meter match on test-set

In [15]:

test_df['mmt'] = test_df['mmt'].astype(int)  # ensure numeric 0/1

result_test_mmt = (
    test_df.groupby('gsy')
    .agg(
        mmt_ones=('mmt', 'sum'),  # total 1s
        count=('mmt', 'size')  # total rows in group
    )
)

# percentage of 1s within each gmt group
result_test_mmt['mmt_pct'] = result_test_mmt['mmt_ones'] / result_test_mmt['count'] * 100

In [16]:
result_test_mmt

     mmt_ones  count     mmt_pct
gsy
3           8      8  100.000000
4          18     18  100.000000
5          54     59   91.525424
6         114    114  100.000000
7          57     60   95.000000
8         246    266   92.481203
10         67     69   97.101449
11        146    163   89.570552
12         14     20   70.000000
14         22     23   95.652174